### PR TITLE
Updated Progress, DateConverter

### PR DESCRIPTION
**Pull request by NickSNFK**
-Few bug fixes with progress, still have an issue with getCurrentUser method in progressActivity.
-added date converter methods
-chnaged Habit Event class(added attributes)
-placeholder tranistion between ahbit lists and view/edit
-added testing gradle dependancies
-removed some testing lines
issues: #71 #30

### CODE REVIEW

**Comment by NickSNFK** [comment]
I think you should keep the code that is from dev for the conflict.

**Review by johnzhang27 — CHANGES_REQUESTED** [review]
For HomActivity and ListActivity, I noticed you hardcoded the user name to 'user1'. I think we Should use SharedInfo.getInstance().getCurrentUser.getUserName().

Also, don't merge before my PR(#108) get merged. I noticed you commit my old version DateConverter class which means there could be more conflicts shows up after #108 get merged.

**Comment by NickSNFK** [comment]
I will commit those changes right now.

**Review by johnzhang27 — APPROVED** [review]
I think it is good now. But please wait until #108 get merged.

**Review by zarifmahfuz — APPROVED** [review]
Good. I am able to build and run the tests.

**Pull request merged**
